/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.HomeAddress;
import model.Person;
import model.PersonDirectory;
import model.WorkAddress;

/**
 *
 * @author hyZHO
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    PersonDirectory personDirectory;
    Person person;
    HomeAddress homeAddress;
    
    public MainJFrame() {
        initComponents();
//        this.person = person;
        this.personDirectory = new PersonDirectory();
        this.homeAddress = homeAddress;

//        initialPersons();
//   
        HomeAddress p1ha = new HomeAddress("123 Main St","4A","Boston","00000");
        WorkAddress p1wa = new WorkAddress("234 Tech Blvd","6B","Cambridge","12345");
        Person p1 = new Person("Hongyi","Zhou","000-00-0000","A1234567",p1ha, p1wa);

        HomeAddress p2ha = new HomeAddress("456 Oak St", "2C", "Somerville", "54321");
        WorkAddress p2wa = new WorkAddress("789 Innovation Ave", "8D", "Boston", "11111");
        Person p2 = new Person("John", "Doe", "111-11-1111", "B9876543", p2ha, p2wa);

        HomeAddress p3ha = new HomeAddress("789 Pine St", "1A", "Cambridge", "22222");
        WorkAddress p3wa = new WorkAddress("321 Tech Blvd", "5E", "Somerville", "33333");
        Person p3 = new Person("Jane", "Smith", "222-22-2222", "C3456789", p3ha, p3wa);

        HomeAddress p4ha = new HomeAddress("987 Elm St", "3B", "Somerville", "44444");
        WorkAddress p4wa = new WorkAddress("654 Main Blvd", "7F", "Cambridge", "55555");
        Person p4 = new Person("Alice", "Johnson", "333-33-3333", "D5678901", p4ha, p4wa);

        HomeAddress p5ha = new HomeAddress("567 Birch St", "5D", "Boston", "66666");
        WorkAddress p5wa = new WorkAddress("876 Innovation Ave", "4G", "Somerville", "77777");
        Person p5 = new Person("Bob", "Williams", "444-44-4444", "E1234567", p5ha, p5wa);

        HomeAddress p6ha = new HomeAddress("111 Cedar St", "6F", "Cambridge", "88888");
        WorkAddress p6wa = new WorkAddress("222 Tech Blvd", "2H", "Boston", "99999");
        Person p6 = new Person("Emily", "Davis", "555-55-5555", "F2345678", p6ha, p6wa);
//        p1.setFirstName("Hongyi");
//        p1.setLastName("Zhou");
//        p1.setSSN("000-00-0000");
//        p1.setLicenseNumber("A1234567");
        
//        p1ha.sethStreet("123 Main St");
//        p1ha.sethUnit("4A");
//        p1ha.sethCity("Boston");
//        p1ha.sethZip("00000");
//        p1.setHomeAddress(p1ha);
//        
        
//        p1wa.setwStreet("234 Tech Blvd");
//        p1wa.setwUnit("6B");
//        p1wa.setwCity("Cambridge");
//        p1wa.setwZip("12345");
//        p1.setWorkAddress(p1wa);
//        personDirectory.CreatePerson(p1);
        
        personDirectory.CreatePerson(p1);
        personDirectory.CreatePerson(p2);
        personDirectory.CreatePerson(p3);
        personDirectory.CreatePerson(p4);
        personDirectory.CreatePerson(p5);
        personDirectory.CreatePerson(p6);
//          personDirectory.add(p1);
//        personDirectory.CreatePerson(p2);
//        personDirectory.CreatePerson(p3);
//        personDirectory.CreatePerson(p4);
//        personDirectory.CreatePerson(p5);
//        personDirectory.CreatePerson(p6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdd_person = new javax.swing.JButton();
        btnList_person = new javax.swing.JButton();
        txtSearchPerson = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Personal Profile");

        btnAdd_person.setText("Add Person");
        btnAdd_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_personActionPerformed(evt);
            }
        });

        btnList_person.setText("List Person");
        btnList_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnList_personActionPerformed(evt);
            }
        });

        txtSearchPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchPersonActionPerformed(evt);
            }
        });

        btnSearch.setText("Search for Person");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAdd_person, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnList_person, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearchPerson))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd_person, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnList_person, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(txtSearchPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_personActionPerformed
        // TODO add your handling code here:
        AddJPanel addPanel = new AddJPanel(userProcessContainer,personDirectory);
        userProcessContainer.add("AddJPanel", addPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
//        jSplitPane1.setRightComponent(addPanel); 
//        
//        AddJPanel panel = new AddJPanel(userProcessContainer, personDirectory);
//        userProcessContainer.add("AddJPanel", panel);
        
    }//GEN-LAST:event_btnAdd_personActionPerformed

    private void btnList_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnList_personActionPerformed
        // TODO add your handling code here:
        ListJPanel listPanel = new ListJPanel(userProcessContainer,personDirectory);
        userProcessContainer.add("ListJPanel", listPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnList_personActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Person result = personDirectory.searchPerson(txtSearchPerson.getText());
//        Account result = accountDirectory.searchAccount(txtAccountNumber.getText());
        if(result == null){
            JOptionPane.showMessageDialog(null, "The name or street you entered does not exsit.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            AddJPanel addpanel = new AddJPanel(userProcessContainer, result, personDirectory);
            userProcessContainer.add("ListJPanel", addpanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            JOptionPane.showMessageDialog(this, "Search completed. Here are the complete profile of the person.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchPersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
//    public void initialPersons(){
//        String[] firstNames = {"Hongyi", "John", "Emily", "David", "Sophia", "Ella"};
//        String[] lastNames = {"Zhou", "Smith", "Johnson", "Williams", "Brown", "Davis"};
//        String[] ssn = {"000-00-0000", "111-11-1111", "222-22-2222", "333-33-3333", "444-44-4444", "555-55-5555"};
//        String[] licenseNumbers = {"A1234567", "B2345678", "C3456789", "D4567890", "E5678901", "F6789012"};
//        
//        for (int i=0; i<6; i++){
//            Person p = personDirectory.addPersons();
//            p.setFirstName(firstNames[i]);
//            p.setLastName(lastNames[i]);
//            p.setSSN(ssn[i]);
//            p.setLicenseNumber(licenseNumbers[i]);
//            
//            HomeAddress ha = new HomeAddress();
//            ha.sethStreet("Street"+(i+1));
//            ha.sethCity("city"+(i+1));
//            ha.sethZip("Zip"+(i+1));
//            ha.sethUnit("Unit"+(i+1));
//            p.setHomeAddress(ha);
//        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_person;
    private javax.swing.JButton btnList_person;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField txtSearchPerson;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
