/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

//import model.BankAccountDatabase;
import model.BankAccountDatabase;
import model.HomeAddressDatabase;
import model.LocalAddressDatabase;
import model.PersonDatabase;

/**
 *
 * @author hyZHO
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    PersonDatabase person;
    HomeAddressDatabase home;
    LocalAddressDatabase local;
    BankAccountDatabase account;
    
    
    public MainJFrame() {
        initComponents();
        
        person = new PersonDatabase();
        home = new HomeAddressDatabase();
        local = new LocalAddressDatabase();
        account = new BankAccountDatabase();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        workArea1 = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCreate_person = new javax.swing.JButton();
        btnView_person = new javax.swing.JButton();
        btnView_home = new javax.swing.JButton();
        btnCreate_home = new javax.swing.JButton();
        btnCreate_local = new javax.swing.JButton();
        btnView_local = new javax.swing.JButton();
        btnCreate_account = new javax.swing.JButton();
        btnView_account = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout workArea1Layout = new javax.swing.GroupLayout(workArea1);
        workArea1.setLayout(workArea1Layout);
        workArea1Layout.setHorizontalGroup(
            workArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        workArea1Layout.setVerticalGroup(
            workArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(workArea);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Personal Profile");

        btnCreate_person.setText("Create Person");
        btnCreate_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate_personActionPerformed(evt);
            }
        });

        btnView_person.setText("View Person");
        btnView_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_personActionPerformed(evt);
            }
        });

        btnView_home.setText("View Home Address");
        btnView_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_homeActionPerformed(evt);
            }
        });

        btnCreate_home.setText("Create Home Address");
        btnCreate_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate_homeActionPerformed(evt);
            }
        });

        btnCreate_local.setText("Create Local Address");
        btnCreate_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate_localActionPerformed(evt);
            }
        });

        btnView_local.setText("View Local Address");
        btnView_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_localActionPerformed(evt);
            }
        });

        btnCreate_account.setText("Create Bank Account");
        btnCreate_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate_accountActionPerformed(evt);
            }
        });

        btnView_account.setText("View Bank Account");
        btnView_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_accountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate_person, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView_person, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreate_local, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView_local, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreate_account, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView_account, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate_home, btnCreate_person, btnView_home, btnView_person});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreate_person, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView_person, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnCreate_home, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView_home, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCreate_local, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView_local, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnCreate_account, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView_account, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreate_home, btnCreate_person, btnView_home, btnView_person});

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreate_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate_personActionPerformed
        // TODO add your handling code here:
        
        Person_CreateJPanel person_createPanel = new Person_CreateJPanel(person);
        splitPane.setRightComponent(person_createPanel); 
        
    }//GEN-LAST:event_btnCreate_personActionPerformed

    private void btnView_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_personActionPerformed
        // TODO add your handling code here:
        
        Person_ViewJPanel person_viewPanel = new Person_ViewJPanel(person);
        splitPane.setRightComponent(person_viewPanel);  
        
    }//GEN-LAST:event_btnView_personActionPerformed

    private void btnCreate_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate_homeActionPerformed
        // TODO add your handling code here:
        
        CreateJPanel createPanel = new CreateJPanel(home);
        splitPane.setRightComponent(createPanel);
        
    }//GEN-LAST:event_btnCreate_homeActionPerformed

    private void btnView_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_homeActionPerformed
        // TODO add your handling code here:
        
        ViewJPanel viewPanel = new ViewJPanel(home);
        splitPane.setRightComponent(viewPanel);
        
    }//GEN-LAST:event_btnView_homeActionPerformed

    private void btnCreate_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate_localActionPerformed
        // TODO add your handling code here:
        
        Local_CreateJPanel local_createPanel = new Local_CreateJPanel(local);
        splitPane.setRightComponent(local_createPanel);        
        
        
    }//GEN-LAST:event_btnCreate_localActionPerformed

    private void btnView_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_localActionPerformed
        // TODO add your handling code here:
        
        Local_ViewJPanel local_viewPanel = new Local_ViewJPanel(local);
        splitPane.setRightComponent(local_viewPanel);      
        
    }//GEN-LAST:event_btnView_localActionPerformed

    private void btnCreate_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate_accountActionPerformed
        // TODO add your handling code here:
        
        Account_CreateJPanel account_createPanel = new Account_CreateJPanel(account);
        splitPane.setRightComponent(account_createPanel);  
        
    }//GEN-LAST:event_btnCreate_accountActionPerformed

    private void btnView_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_accountActionPerformed
        // TODO add your handling code here:
        
        Account_ViewJPanel account_viewPanel = new Account_ViewJPanel(account);
        splitPane.setRightComponent(account_viewPanel);  
        
    }//GEN-LAST:event_btnView_accountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate_account;
    private javax.swing.JButton btnCreate_home;
    private javax.swing.JButton btnCreate_local;
    private javax.swing.JButton btnCreate_person;
    private javax.swing.JButton btnView_account;
    private javax.swing.JButton btnView_home;
    private javax.swing.JButton btnView_local;
    private javax.swing.JButton btnView_person;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    private javax.swing.JPanel workArea1;
    // End of variables declaration//GEN-END:variables
}
